const loansched = {
    "id": 13979,
    "accountNo": "000013979",
    "status": {
        "id": 300,
        "code": "loanStatusType.active",
        "value": "Active",
        "pendingApproval": false,
        "waitingForDisbursal": false,
        "active": true,
        "closedObligationsMet": false,
        "closedWrittenOff": false,
        "closedRescheduled": false,
        "closed": false,
        "overpaid": false
    },
    "clientId": 5,
    "clientAccountNo": "000000005",
    "clientName": "Agustin Palacios  Aguado",
    "clientOfficeId": 44,
    "loanProductId": 19,
    "loanProductName": "CREDITO SOLIDARIO",
    "isLoanProductLinkedToFloatingRate": false,
    "fundId": 2,
    "fundName": "BAJIO",
    "loanPurposeId": 21,
    "loanPurposeName": "ADQUIRIR O COMPRAR MERCANCIA",
    "loanOfficerId": 0,
    "loanOfficerName": null,
    "loanType": {
        "id": 1,
        "code": "accountType.individual",
        "value": "Individual"
    },
    "currency": {
        "code": "MXN",
        "name": "Mexican Peso",
        "decimalPlaces": 2,
        "inMultiplesOf": 1,
        "displaySymbol": "$",
        "nameCode": "currency.MXN",
        "displayLabel": "Mexican Peso ($)"
    },
    "principal": 15000.000000,
    "approvedPrincipal": 15000.000000,
    "proposedPrincipal": 15000.000000,
    "termFrequency": 16,
    "termPeriodFrequencyType": {
        "id": 1,
        "code": "termFrequency.periodFrequencyType.weeks",
        "value": "Weeks"
    },
    "numberOfRepayments": 16,
    "repaymentEvery": 1,
    "repaymentFrequencyType": {
        "id": 1,
        "code": "repaymentFrequency.periodFrequencyType.weeks",
        "value": "Weeks"
    },
    "repaymentFrequencyNthDayType": null,
    "repaymentFrequencyDayOfWeekType": null,
    "interestRatePerPeriod": 91.210000,
    "interestRateFrequencyType": {
        "id": 3,
        "code": "interestRateFrequency.periodFrequencyType.years",
        "value": "Per year"
    },
    "annualInterestRate": 91.210000,
    "isFloatingInterestRate": false,
    "amortizationType": {
        "id": 1,
        "code": "amortizationType.equal.installments",
        "value": "Equal installments"
    },
    "interestType": {
        "id": 0,
        "code": "interestType.declining.balance",
        "value": "Declining Balance"
    },
    "interestCalculationPeriodType": {
        "id": 0,
        "code": "interestCalculationPeriodType.daily",
        "value": "Daily"
    },
    "allowPartialPeriodInterestCalcualtion": false,
    "inArrearsTolerance": 0.000000,
    "transactionProcessingStrategyId": 1,
    "graceOnArrearsAgeing": 1,
    "syncDisbursementWithMeeting": false,
    "timeline": {
        "submittedOnDate": [
            2020,
            9,
            17
        ],
        "submittedByUsername": "mifos",
        "submittedByFirstname": "App",
        "submittedByLastname": "Administrator",
        "approvedOnDate": [
            2020,
            9,
            17
        ],
        "approvedByUsername": "mifos",
        "approvedByFirstname": "App",
        "approvedByLastname": "Administrator",
        "expectedDisbursementDate": [
            2020,
            9,
            17
        ],
        "actualDisbursementDate": [
            2020,
            9,
            17
        ],
        "disbursedByUsername": "mifos",
        "disbursedByFirstname": "App",
        "disbursedByLastname": "Administrator",
        "expectedMaturityDate": [
            2021,
            1,
            7
        ]
    },
    "summary": {
        "currency": {
            "code": "MXN",
            "name": "Mexican Peso",
            "decimalPlaces": 2,
            "inMultiplesOf": 1,
            "displaySymbol": "$",
            "nameCode": "currency.MXN",
            "displayLabel": "Mexican Peso ($)"
        },
        "principalDisbursed": 15000.000000,
        "principalPaid": 0.000000,
        "principalWrittenOff": 0.000000,
        "principalOutstanding": 15000.000000,
        "principalOverdue": 802.790000,
        "interestCharged": 2348.350000,
        "interestPaid": 0.000000,
        "interestWaived": 2348.350000,
        "interestWrittenOff": 0.000000,
        "interestOutstanding": 0.000000,
        "interestOverdue": 0.000000,
        "feeChargesCharged": 0.000000,
        "feeChargesDueAtDisbursementCharged": 0.000000,
        "feeChargesPaid": 0.000000,
        "feeChargesWaived": 0.000000,
        "feeChargesWrittenOff": 0.000000,
        "feeChargesOutstanding": 0.000000,
        "feeChargesOverdue": 0.000000,
        "penaltyChargesCharged": 0.000000,
        "penaltyChargesPaid": 0.000000,
        "penaltyChargesWaived": 0.000000,
        "penaltyChargesWrittenOff": 0.000000,
        "penaltyChargesOutstanding": 0.000000,
        "penaltyChargesOverdue": 0.000000,
        "totalExpectedRepayment": 17724.090000,
        "totalRepayment": 0.000000,
        "totalExpectedCostOfLoan": 2348.350000,
        "totalCostOfLoan": 0.000000,
        "totalWaived": 2724.086000,
        "totalWrittenOff": 0.000000,
        "totalOutstanding": 15375.740000,
        "totalOverdue": 802.790000,
        "overdueSinceDate": [
            2020,
            9,
            24
        ],
        "writeoffReasonId": 0,
        "writeoffReason": null
    },
    "repaymentSchedule": {
        "currency": {
            "code": "MXN",
            "name": "Mexican Peso",
            "decimalPlaces": 2,
            "inMultiplesOf": 1,
            "displaySymbol": "$",
            "nameCode": "currency.MXN",
            "displayLabel": "Mexican Peso ($)"
        },
        "loanTermInDays": 112,
        "totalPrincipalDisbursed": 15000.00,
        "totalPrincipalExpected": 15000.00,
        "totalPrincipalPaid": 0.00,
        "totalInterestCharged": 2348.35,
        "totalFeeChargesCharged": 0.00,
        "totalPenaltyChargesCharged": 0.00,
        "totalWaived": 2348.35,
        "totalWrittenOff": 0.00,
        "totalRepaymentExpected": 17724.09,
        "totalRepayment": 0.00,
        "totalPaidInAdvance": 0.00,
        "totalPaidLate": 0.00,
        "totalOutstanding": 15375.74,
        "totalTaxes": 375.74,
        "periods": [
            {
                "dueDate": [
                    2020,
                    9,
                    17
                ],
                "principalDisbursed": 15000.000000,
                "principalLoanBalanceOutstanding": 15000.000000,
                "period": 0,
                "fromDate": null,
                "obligationsMetOnDate": null,
                "complete": false,
                "daysInPeriod": 0,
                "principalOriginalDue": 0.0,
                "principalDue": 0.0,
                "principalPaid": 0.0,
                "principalWrittenOff": 0.0,
                "principalOutstanding": 0.0,
                "taxOnInterestDue": 0.0,
                "taxOnInterestPaid": 0.0,
                "taxOnInterestOutstanding": 0.0,
                "interestOriginalDue": 0.0,
                "interestDue": 0.0,
                "interestPaid": 0.0,
                "interestWaived": 0.0,
                "interestWrittenOff": 0.0,
                "interestOutstanding": 0.0,
                "feeChargesDue": 0.000000,
                "feeChargesPaid": 0.000000,
                "feeChargesWaived": 0.0,
                "feeChargesWrittenOff": 0.0,
                "feeChargesOutstanding": 0.0,
                "penaltyChargesDue": 0.0,
                "penaltyChargesPaid": 0.0,
                "penaltyChargesWaived": 0.0,
                "penaltyChargesWrittenOff": 0.0,
                "penaltyChargesOutstanding": 0.0,
                "totalOriginalDueForPeriod": 0.000000,
                "totalDueForPeriod": 0.000000,
                "totalPaidForPeriod": 0.000000,
                "totalPaidInAdvanceForPeriod": 0.0,
                "totalPaidLateForPeriod": 0.0,
                "totalWaivedForPeriod": 0.0,
                "totalWrittenOffForPeriod": 0.0,
                "totalOutstandingForPeriod": 0.0,
                "totalActualCostOfLoanForPeriod": 0.000000,
                "totalOverdue": 0.0,
                "totalInstallmentAmountForPeriod": 0.0
            },
            {
                "dueDate": [
                    2020,
                    9,
                    24
                ],
                "principalDisbursed": 0.0,
                "principalLoanBalanceOutstanding": 14197.210000,
                "period": 1,
                "fromDate": [
                    2020,
                    9,
                    17
                ],
                "obligationsMetOnDate": null,
                "complete": false,
                "daysInPeriod": 7,
                "principalOriginalDue": 802.790000,
                "principalDue": 802.790000,
                "principalPaid": 0.0,
                "principalWrittenOff": 0.0,
                "principalOutstanding": 802.790000,
                "taxOnInterestDue": 42.100000,
                "taxOnInterestPaid": 0.0,
                "taxOnInterestOutstanding": 42.100000,
                "interestOriginalDue": 263.110000,
                "interestDue": 263.110000,
                "interestPaid": 0.0,
                "interestWaived": 263.110000,
                "interestWrittenOff": 0.0,
                "interestOutstanding": 0.000000,
                "feeChargesDue": 0.0,
                "feeChargesPaid": 0.0,
                "feeChargesWaived": 0.0,
                "feeChargesWrittenOff": 0.0,
                "feeChargesOutstanding": 0.0,
                "penaltyChargesDue": 0.0,
                "penaltyChargesPaid": 0.0,
                "penaltyChargesWaived": 0.0,
                "penaltyChargesWrittenOff": 0.0,
                "penaltyChargesOutstanding": 0.0,
                "totalOriginalDueForPeriod": 1108.000000,
                "totalDueForPeriod": 1108.000000,
                "totalPaidForPeriod": 0.0,
                "totalPaidInAdvanceForPeriod": 0.0,
                "totalPaidLateForPeriod": 0.0,
                "totalWaivedForPeriod": 263.110000,
                "totalWrittenOffForPeriod": 0.0,
                "totalOutstandingForPeriod": 844.890000,
                "totalActualCostOfLoanForPeriod": 0.000000,
                "totalOverdue": 844.890000,
                "totalInstallmentAmountForPeriod": 1108.00
            },
            {
                "dueDate": [
                    2020,
                    10,
                    1
                ],
                "principalDisbursed": 0.0,
                "principalLoanBalanceOutstanding": 13378.070000,
                "period": 2,
                "fromDate": [
                    2020,
                    9,
                    24
                ],
                "obligationsMetOnDate": null,
                "complete": false,
                "daysInPeriod": 7,
                "principalOriginalDue": 819.140000,
                "principalDue": 819.140000,
                "principalPaid": 0.0,
                "principalWrittenOff": 0.0,
                "principalOutstanding": 819.140000,
                "taxOnInterestDue": 39.840000,
                "taxOnInterestPaid": 0.0,
                "taxOnInterestOutstanding": 39.840000,
                "interestOriginalDue": 249.020000,
                "interestDue": 249.020000,
                "interestPaid": 0.0,
                "interestWaived": 249.020000,
                "interestWrittenOff": 0.0,
                "interestOutstanding": 0.000000,
                "feeChargesDue": 0.0,
                "feeChargesPaid": 0.0,
                "feeChargesWaived": 0.0,
                "feeChargesWrittenOff": 0.0,
                "feeChargesOutstanding": 0.0,
                "penaltyChargesDue": 0.0,
                "penaltyChargesPaid": 0.0,
                "penaltyChargesWaived": 0.0,
                "penaltyChargesWrittenOff": 0.0,
                "penaltyChargesOutstanding": 0.0,
                "totalOriginalDueForPeriod": 1108.000000,
                "totalDueForPeriod": 1108.000000,
                "totalPaidForPeriod": 0.0,
                "totalPaidInAdvanceForPeriod": 0.0,
                "totalPaidLateForPeriod": 0.0,
                "totalWaivedForPeriod": 249.020000,
                "totalWrittenOffForPeriod": 0.0,
                "totalOutstandingForPeriod": 858.980000,
                "totalActualCostOfLoanForPeriod": 0.000000,
                "totalOverdue": 0.0,
                "totalInstallmentAmountForPeriod": 1108.00
            },
            {
                "dueDate": [
                    2020,
                    10,
                    8
                ],
                "principalDisbursed": 0.0,
                "principalLoanBalanceOutstanding": 12542.280000,
                "period": 3,
                "fromDate": [
                    2020,
                    10,
                    1
                ],
                "obligationsMetOnDate": null,
                "complete": false,
                "daysInPeriod": 7,
                "principalOriginalDue": 835.790000,
                "principalDue": 835.790000,
                "principalPaid": 0.0,
                "principalWrittenOff": 0.0,
                "principalOutstanding": 835.790000,
                "taxOnInterestDue": 37.550000,
                "taxOnInterestPaid": 0.0,
                "taxOnInterestOutstanding": 37.550000,
                "interestOriginalDue": 234.660000,
                "interestDue": 234.660000,
                "interestPaid": 0.0,
                "interestWaived": 234.660000,
                "interestWrittenOff": 0.0,
                "interestOutstanding": 0.000000,
                "feeChargesDue": 0.0,
                "feeChargesPaid": 0.0,
                "feeChargesWaived": 0.0,
                "feeChargesWrittenOff": 0.0,
                "feeChargesOutstanding": 0.0,
                "penaltyChargesDue": 0.0,
                "penaltyChargesPaid": 0.0,
                "penaltyChargesWaived": 0.0,
                "penaltyChargesWrittenOff": 0.0,
                "penaltyChargesOutstanding": 0.0,
                "totalOriginalDueForPeriod": 1108.000000,
                "totalDueForPeriod": 1108.000000,
                "totalPaidForPeriod": 0.0,
                "totalPaidInAdvanceForPeriod": 0.0,
                "totalPaidLateForPeriod": 0.0,
                "totalWaivedForPeriod": 234.660000,
                "totalWrittenOffForPeriod": 0.0,
                "totalOutstandingForPeriod": 873.340000,
                "totalActualCostOfLoanForPeriod": 0.000000,
                "totalOverdue": 0.0,
                "totalInstallmentAmountForPeriod": 1108.00
            },
            {
                "dueDate": [
                    2020,
                    10,
                    15
                ],
                "principalDisbursed": 0.0,
                "principalLoanBalanceOutstanding": 11689.480000,
                "period": 4,
                "fromDate": [
                    2020,
                    10,
                    8
                ],
                "obligationsMetOnDate": null,
                "complete": false,
                "daysInPeriod": 7,
                "principalOriginalDue": 852.800000,
                "principalDue": 852.800000,
                "principalPaid": 0.0,
                "principalWrittenOff": 0.0,
                "principalOutstanding": 852.800000,
                "taxOnInterestDue": 35.200000,
                "taxOnInterestPaid": 0.0,
                "taxOnInterestOutstanding": 35.200000,
                "interestOriginalDue": 220.000000,
                "interestDue": 220.000000,
                "interestPaid": 0.0,
                "interestWaived": 220.000000,
                "interestWrittenOff": 0.0,
                "interestOutstanding": 0.000000,
                "feeChargesDue": 0.0,
                "feeChargesPaid": 0.0,
                "feeChargesWaived": 0.0,
                "feeChargesWrittenOff": 0.0,
                "feeChargesOutstanding": 0.0,
                "penaltyChargesDue": 0.0,
                "penaltyChargesPaid": 0.0,
                "penaltyChargesWaived": 0.0,
                "penaltyChargesWrittenOff": 0.0,
                "penaltyChargesOutstanding": 0.0,
                "totalOriginalDueForPeriod": 1108.000000,
                "totalDueForPeriod": 1108.000000,
                "totalPaidForPeriod": 0.0,
                "totalPaidInAdvanceForPeriod": 0.0,
                "totalPaidLateForPeriod": 0.0,
                "totalWaivedForPeriod": 220.000000,
                "totalWrittenOffForPeriod": 0.0,
                "totalOutstandingForPeriod": 888.000000,
                "totalActualCostOfLoanForPeriod": 0.000000,
                "totalOverdue": 0.0,
                "totalInstallmentAmountForPeriod": 1108.00
            },
            {
                "dueDate": [
                    2020,
                    10,
                    22
                ],
                "principalDisbursed": 0.0,
                "principalLoanBalanceOutstanding": 10819.330000,
                "period": 5,
                "fromDate": [
                    2020,
                    10,
                    15
                ],
                "obligationsMetOnDate": null,
                "complete": false,
                "daysInPeriod": 7,
                "principalOriginalDue": 870.150000,
                "principalDue": 870.150000,
                "principalPaid": 0.0,
                "principalWrittenOff": 0.0,
                "principalOutstanding": 870.150000,
                "taxOnInterestDue": 32.810000,
                "taxOnInterestPaid": 0.0,
                "taxOnInterestOutstanding": 32.810000,
                "interestOriginalDue": 205.040000,
                "interestDue": 205.040000,
                "interestPaid": 0.0,
                "interestWaived": 205.040000,
                "interestWrittenOff": 0.0,
                "interestOutstanding": 0.000000,
                "feeChargesDue": 0.0,
                "feeChargesPaid": 0.0,
                "feeChargesWaived": 0.0,
                "feeChargesWrittenOff": 0.0,
                "feeChargesOutstanding": 0.0,
                "penaltyChargesDue": 0.0,
                "penaltyChargesPaid": 0.0,
                "penaltyChargesWaived": 0.0,
                "penaltyChargesWrittenOff": 0.0,
                "penaltyChargesOutstanding": 0.0,
                "totalOriginalDueForPeriod": 1108.000000,
                "totalDueForPeriod": 1108.000000,
                "totalPaidForPeriod": 0.0,
                "totalPaidInAdvanceForPeriod": 0.0,
                "totalPaidLateForPeriod": 0.0,
                "totalWaivedForPeriod": 205.040000,
                "totalWrittenOffForPeriod": 0.0,
                "totalOutstandingForPeriod": 902.960000,
                "totalActualCostOfLoanForPeriod": 0.000000,
                "totalOverdue": 0.0,
                "totalInstallmentAmountForPeriod": 1108.00
            },
            {
                "dueDate": [
                    2020,
                    10,
                    29
                ],
                "principalDisbursed": 0.0,
                "principalLoanBalanceOutstanding": 9931.470000,
                "period": 6,
                "fromDate": [
                    2020,
                    10,
                    22
                ],
                "obligationsMetOnDate": null,
                "complete": false,
                "daysInPeriod": 7,
                "principalOriginalDue": 887.860000,
                "principalDue": 887.860000,
                "principalPaid": 0.0,
                "principalWrittenOff": 0.0,
                "principalOutstanding": 887.860000,
                "taxOnInterestDue": 30.360000,
                "taxOnInterestPaid": 0.0,
                "taxOnInterestOutstanding": 30.360000,
                "interestOriginalDue": 189.780000,
                "interestDue": 189.780000,
                "interestPaid": 0.0,
                "interestWaived": 189.780000,
                "interestWrittenOff": 0.0,
                "interestOutstanding": 0.000000,
                "feeChargesDue": 0.0,
                "feeChargesPaid": 0.0,
                "feeChargesWaived": 0.0,
                "feeChargesWrittenOff": 0.0,
                "feeChargesOutstanding": 0.0,
                "penaltyChargesDue": 0.0,
                "penaltyChargesPaid": 0.0,
                "penaltyChargesWaived": 0.0,
                "penaltyChargesWrittenOff": 0.0,
                "penaltyChargesOutstanding": 0.0,
                "totalOriginalDueForPeriod": 1108.000000,
                "totalDueForPeriod": 1108.000000,
                "totalPaidForPeriod": 0.0,
                "totalPaidInAdvanceForPeriod": 0.0,
                "totalPaidLateForPeriod": 0.0,
                "totalWaivedForPeriod": 189.780000,
                "totalWrittenOffForPeriod": 0.0,
                "totalOutstandingForPeriod": 918.220000,
                "totalActualCostOfLoanForPeriod": 0.000000,
                "totalOverdue": 0.0,
                "totalInstallmentAmountForPeriod": 1108.00
            },
            {
                "dueDate": [
                    2020,
                    11,
                    5
                ],
                "principalDisbursed": 0.0,
                "principalLoanBalanceOutstanding": 9025.540000,
                "period": 7,
                "fromDate": [
                    2020,
                    10,
                    29
                ],
                "obligationsMetOnDate": null,
                "complete": false,
                "daysInPeriod": 7,
                "principalOriginalDue": 905.930000,
                "principalDue": 905.930000,
                "principalPaid": 0.0,
                "principalWrittenOff": 0.0,
                "principalOutstanding": 905.930000,
                "taxOnInterestDue": 27.870000,
                "taxOnInterestPaid": 0.0,
                "taxOnInterestOutstanding": 27.870000,
                "interestOriginalDue": 174.200000,
                "interestDue": 174.200000,
                "interestPaid": 0.0,
                "interestWaived": 174.200000,
                "interestWrittenOff": 0.0,
                "interestOutstanding": 0.000000,
                "feeChargesDue": 0.0,
                "feeChargesPaid": 0.0,
                "feeChargesWaived": 0.0,
                "feeChargesWrittenOff": 0.0,
                "feeChargesOutstanding": 0.0,
                "penaltyChargesDue": 0.0,
                "penaltyChargesPaid": 0.0,
                "penaltyChargesWaived": 0.0,
                "penaltyChargesWrittenOff": 0.0,
                "penaltyChargesOutstanding": 0.0,
                "totalOriginalDueForPeriod": 1108.000000,
                "totalDueForPeriod": 1108.000000,
                "totalPaidForPeriod": 0.0,
                "totalPaidInAdvanceForPeriod": 0.0,
                "totalPaidLateForPeriod": 0.0,
                "totalWaivedForPeriod": 174.200000,
                "totalWrittenOffForPeriod": 0.0,
                "totalOutstandingForPeriod": 933.800000,
                "totalActualCostOfLoanForPeriod": 0.000000,
                "totalOverdue": 0.0,
                "totalInstallmentAmountForPeriod": 1108.00
            },
            {
                "dueDate": [
                    2020,
                    11,
                    12
                ],
                "principalDisbursed": 0.0,
                "principalLoanBalanceOutstanding": 8101.180000,
                "period": 8,
                "fromDate": [
                    2020,
                    11,
                    5
                ],
                "obligationsMetOnDate": null,
                "complete": false,
                "daysInPeriod": 7,
                "principalOriginalDue": 924.360000,
                "principalDue": 924.360000,
                "principalPaid": 0.0,
                "principalWrittenOff": 0.0,
                "principalOutstanding": 924.360000,
                "taxOnInterestDue": 25.330000,
                "taxOnInterestPaid": 0.0,
                "taxOnInterestOutstanding": 25.330000,
                "interestOriginalDue": 158.310000,
                "interestDue": 158.310000,
                "interestPaid": 0.0,
                "interestWaived": 158.310000,
                "interestWrittenOff": 0.0,
                "interestOutstanding": 0.000000,
                "feeChargesDue": 0.0,
                "feeChargesPaid": 0.0,
                "feeChargesWaived": 0.0,
                "feeChargesWrittenOff": 0.0,
                "feeChargesOutstanding": 0.0,
                "penaltyChargesDue": 0.0,
                "penaltyChargesPaid": 0.0,
                "penaltyChargesWaived": 0.0,
                "penaltyChargesWrittenOff": 0.0,
                "penaltyChargesOutstanding": 0.0,
                "totalOriginalDueForPeriod": 1108.000000,
                "totalDueForPeriod": 1108.000000,
                "totalPaidForPeriod": 0.0,
                "totalPaidInAdvanceForPeriod": 0.0,
                "totalPaidLateForPeriod": 0.0,
                "totalWaivedForPeriod": 158.310000,
                "totalWrittenOffForPeriod": 0.0,
                "totalOutstandingForPeriod": 949.690000,
                "totalActualCostOfLoanForPeriod": 0.000000,
                "totalOverdue": 0.0,
                "totalInstallmentAmountForPeriod": 1108.00
            },
            {
                "dueDate": [
                    2020,
                    11,
                    19
                ],
                "principalDisbursed": 0.0,
                "principalLoanBalanceOutstanding": 7158.020000,
                "period": 9,
                "fromDate": [
                    2020,
                    11,
                    12
                ],
                "obligationsMetOnDate": null,
                "complete": false,
                "daysInPeriod": 7,
                "principalOriginalDue": 943.160000,
                "principalDue": 943.160000,
                "principalPaid": 0.0,
                "principalWrittenOff": 0.0,
                "principalOutstanding": 943.160000,
                "taxOnInterestDue": 22.740000,
                "taxOnInterestPaid": 0.0,
                "taxOnInterestOutstanding": 22.740000,
                "interestOriginalDue": 142.100000,
                "interestDue": 142.100000,
                "interestPaid": 0.0,
                "interestWaived": 142.100000,
                "interestWrittenOff": 0.0,
                "interestOutstanding": 0.000000,
                "feeChargesDue": 0.0,
                "feeChargesPaid": 0.0,
                "feeChargesWaived": 0.0,
                "feeChargesWrittenOff": 0.0,
                "feeChargesOutstanding": 0.0,
                "penaltyChargesDue": 0.0,
                "penaltyChargesPaid": 0.0,
                "penaltyChargesWaived": 0.0,
                "penaltyChargesWrittenOff": 0.0,
                "penaltyChargesOutstanding": 0.0,
                "totalOriginalDueForPeriod": 1108.000000,
                "totalDueForPeriod": 1108.000000,
                "totalPaidForPeriod": 0.0,
                "totalPaidInAdvanceForPeriod": 0.0,
                "totalPaidLateForPeriod": 0.0,
                "totalWaivedForPeriod": 142.100000,
                "totalWrittenOffForPeriod": 0.0,
                "totalOutstandingForPeriod": 965.900000,
                "totalActualCostOfLoanForPeriod": 0.000000,
                "totalOverdue": 0.0,
                "totalInstallmentAmountForPeriod": 1108.00
            },
            {
                "dueDate": [
                    2020,
                    11,
                    26
                ],
                "principalDisbursed": 0.0,
                "principalLoanBalanceOutstanding": 6195.660000,
                "period": 10,
                "fromDate": [
                    2020,
                    11,
                    19
                ],
                "obligationsMetOnDate": null,
                "complete": false,
                "daysInPeriod": 7,
                "principalOriginalDue": 962.360000,
                "principalDue": 962.360000,
                "principalPaid": 0.0,
                "principalWrittenOff": 0.0,
                "principalOutstanding": 962.360000,
                "taxOnInterestDue": 20.090000,
                "taxOnInterestPaid": 0.0,
                "taxOnInterestOutstanding": 20.090000,
                "interestOriginalDue": 125.550000,
                "interestDue": 125.550000,
                "interestPaid": 0.0,
                "interestWaived": 125.550000,
                "interestWrittenOff": 0.0,
                "interestOutstanding": 0.000000,
                "feeChargesDue": 0.0,
                "feeChargesPaid": 0.0,
                "feeChargesWaived": 0.0,
                "feeChargesWrittenOff": 0.0,
                "feeChargesOutstanding": 0.0,
                "penaltyChargesDue": 0.0,
                "penaltyChargesPaid": 0.0,
                "penaltyChargesWaived": 0.0,
                "penaltyChargesWrittenOff": 0.0,
                "penaltyChargesOutstanding": 0.0,
                "totalOriginalDueForPeriod": 1108.000000,
                "totalDueForPeriod": 1108.000000,
                "totalPaidForPeriod": 0.0,
                "totalPaidInAdvanceForPeriod": 0.0,
                "totalPaidLateForPeriod": 0.0,
                "totalWaivedForPeriod": 125.550000,
                "totalWrittenOffForPeriod": 0.0,
                "totalOutstandingForPeriod": 982.450000,
                "totalActualCostOfLoanForPeriod": 0.000000,
                "totalOverdue": 0.0,
                "totalInstallmentAmountForPeriod": 1108.00
            },
            {
                "dueDate": [
                    2020,
                    12,
                    3
                ],
                "principalDisbursed": 0.0,
                "principalLoanBalanceOutstanding": 5213.720000,
                "period": 11,
                "fromDate": [
                    2020,
                    11,
                    26
                ],
                "obligationsMetOnDate": null,
                "complete": false,
                "daysInPeriod": 7,
                "principalOriginalDue": 981.940000,
                "principalDue": 981.940000,
                "principalPaid": 0.0,
                "principalWrittenOff": 0.0,
                "principalOutstanding": 981.940000,
                "taxOnInterestDue": 17.390000,
                "taxOnInterestPaid": 0.0,
                "taxOnInterestOutstanding": 17.390000,
                "interestOriginalDue": 108.670000,
                "interestDue": 108.670000,
                "interestPaid": 0.0,
                "interestWaived": 108.670000,
                "interestWrittenOff": 0.0,
                "interestOutstanding": 0.000000,
                "feeChargesDue": 0.0,
                "feeChargesPaid": 0.0,
                "feeChargesWaived": 0.0,
                "feeChargesWrittenOff": 0.0,
                "feeChargesOutstanding": 0.0,
                "penaltyChargesDue": 0.0,
                "penaltyChargesPaid": 0.0,
                "penaltyChargesWaived": 0.0,
                "penaltyChargesWrittenOff": 0.0,
                "penaltyChargesOutstanding": 0.0,
                "totalOriginalDueForPeriod": 1108.000000,
                "totalDueForPeriod": 1108.000000,
                "totalPaidForPeriod": 0.0,
                "totalPaidInAdvanceForPeriod": 0.0,
                "totalPaidLateForPeriod": 0.0,
                "totalWaivedForPeriod": 108.670000,
                "totalWrittenOffForPeriod": 0.0,
                "totalOutstandingForPeriod": 999.330000,
                "totalActualCostOfLoanForPeriod": 0.000000,
                "totalOverdue": 0.0,
                "totalInstallmentAmountForPeriod": 1108.00
            },
            {
                "dueDate": [
                    2020,
                    12,
                    10
                ],
                "principalDisbursed": 0.0,
                "principalLoanBalanceOutstanding": 4211.800000,
                "period": 12,
                "fromDate": [
                    2020,
                    12,
                    3
                ],
                "obligationsMetOnDate": null,
                "complete": false,
                "daysInPeriod": 7,
                "principalOriginalDue": 1001.920000,
                "principalDue": 1001.920000,
                "principalPaid": 0.0,
                "principalWrittenOff": 0.0,
                "principalOutstanding": 1001.920000,
                "taxOnInterestDue": 14.630000,
                "taxOnInterestPaid": 0.0,
                "taxOnInterestOutstanding": 14.630000,
                "interestOriginalDue": 91.450000,
                "interestDue": 91.450000,
                "interestPaid": 0.0,
                "interestWaived": 91.450000,
                "interestWrittenOff": 0.0,
                "interestOutstanding": 0.000000,
                "feeChargesDue": 0.0,
                "feeChargesPaid": 0.0,
                "feeChargesWaived": 0.0,
                "feeChargesWrittenOff": 0.0,
                "feeChargesOutstanding": 0.0,
                "penaltyChargesDue": 0.0,
                "penaltyChargesPaid": 0.0,
                "penaltyChargesWaived": 0.0,
                "penaltyChargesWrittenOff": 0.0,
                "penaltyChargesOutstanding": 0.0,
                "totalOriginalDueForPeriod": 1108.000000,
                "totalDueForPeriod": 1108.000000,
                "totalPaidForPeriod": 0.0,
                "totalPaidInAdvanceForPeriod": 0.0,
                "totalPaidLateForPeriod": 0.0,
                "totalWaivedForPeriod": 91.450000,
                "totalWrittenOffForPeriod": 0.0,
                "totalOutstandingForPeriod": 1016.550000,
                "totalActualCostOfLoanForPeriod": 0.000000,
                "totalOverdue": 0.0,
                "totalInstallmentAmountForPeriod": 1108.00
            },
            {
                "dueDate": [
                    2020,
                    12,
                    17
                ],
                "principalDisbursed": 0.0,
                "principalLoanBalanceOutstanding": 3189.500000,
                "period": 13,
                "fromDate": [
                    2020,
                    12,
                    10
                ],
                "obligationsMetOnDate": null,
                "complete": false,
                "daysInPeriod": 7,
                "principalOriginalDue": 1022.300000,
                "principalDue": 1022.300000,
                "principalPaid": 0.0,
                "principalWrittenOff": 0.0,
                "principalOutstanding": 1022.300000,
                "taxOnInterestDue": 11.820000,
                "taxOnInterestPaid": 0.0,
                "taxOnInterestOutstanding": 11.820000,
                "interestOriginalDue": 73.880000,
                "interestDue": 73.880000,
                "interestPaid": 0.0,
                "interestWaived": 73.880000,
                "interestWrittenOff": 0.0,
                "interestOutstanding": 0.000000,
                "feeChargesDue": 0.0,
                "feeChargesPaid": 0.0,
                "feeChargesWaived": 0.0,
                "feeChargesWrittenOff": 0.0,
                "feeChargesOutstanding": 0.0,
                "penaltyChargesDue": 0.0,
                "penaltyChargesPaid": 0.0,
                "penaltyChargesWaived": 0.0,
                "penaltyChargesWrittenOff": 0.0,
                "penaltyChargesOutstanding": 0.0,
                "totalOriginalDueForPeriod": 1108.000000,
                "totalDueForPeriod": 1108.000000,
                "totalPaidForPeriod": 0.0,
                "totalPaidInAdvanceForPeriod": 0.0,
                "totalPaidLateForPeriod": 0.0,
                "totalWaivedForPeriod": 73.880000,
                "totalWrittenOffForPeriod": 0.0,
                "totalOutstandingForPeriod": 1034.120000,
                "totalActualCostOfLoanForPeriod": 0.000000,
                "totalOverdue": 0.0,
                "totalInstallmentAmountForPeriod": 1108.00
            },
            {
                "dueDate": [
                    2020,
                    12,
                    24
                ],
                "principalDisbursed": 0.0,
                "principalLoanBalanceOutstanding": 2146.400000,
                "period": 14,
                "fromDate": [
                    2020,
                    12,
                    17
                ],
                "obligationsMetOnDate": null,
                "complete": false,
                "daysInPeriod": 7,
                "principalOriginalDue": 1043.100000,
                "principalDue": 1043.100000,
                "principalPaid": 0.0,
                "principalWrittenOff": 0.0,
                "principalOutstanding": 1043.100000,
                "taxOnInterestDue": 8.950000,
                "taxOnInterestPaid": 0.0,
                "taxOnInterestOutstanding": 8.950000,
                "interestOriginalDue": 55.950000,
                "interestDue": 55.950000,
                "interestPaid": 0.0,
                "interestWaived": 55.950000,
                "interestWrittenOff": 0.0,
                "interestOutstanding": 0.000000,
                "feeChargesDue": 0.0,
                "feeChargesPaid": 0.0,
                "feeChargesWaived": 0.0,
                "feeChargesWrittenOff": 0.0,
                "feeChargesOutstanding": 0.0,
                "penaltyChargesDue": 0.0,
                "penaltyChargesPaid": 0.0,
                "penaltyChargesWaived": 0.0,
                "penaltyChargesWrittenOff": 0.0,
                "penaltyChargesOutstanding": 0.0,
                "totalOriginalDueForPeriod": 1108.000000,
                "totalDueForPeriod": 1108.000000,
                "totalPaidForPeriod": 0.0,
                "totalPaidInAdvanceForPeriod": 0.0,
                "totalPaidLateForPeriod": 0.0,
                "totalWaivedForPeriod": 55.950000,
                "totalWrittenOffForPeriod": 0.0,
                "totalOutstandingForPeriod": 1052.050000,
                "totalActualCostOfLoanForPeriod": 0.000000,
                "totalOverdue": 0.0,
                "totalInstallmentAmountForPeriod": 1108.00
            },
            {
                "dueDate": [
                    2020,
                    12,
                    31
                ],
                "principalDisbursed": 0.0,
                "principalLoanBalanceOutstanding": 1082.070000,
                "period": 15,
                "fromDate": [
                    2020,
                    12,
                    24
                ],
                "obligationsMetOnDate": null,
                "complete": false,
                "daysInPeriod": 7,
                "principalOriginalDue": 1064.330000,
                "principalDue": 1064.330000,
                "principalPaid": 0.0,
                "principalWrittenOff": 0.0,
                "principalOutstanding": 1064.330000,
                "taxOnInterestDue": 6.020000,
                "taxOnInterestPaid": 0.0,
                "taxOnInterestOutstanding": 6.020000,
                "interestOriginalDue": 37.650000,
                "interestDue": 37.650000,
                "interestPaid": 0.0,
                "interestWaived": 37.650000,
                "interestWrittenOff": 0.0,
                "interestOutstanding": 0.000000,
                "feeChargesDue": 0.0,
                "feeChargesPaid": 0.0,
                "feeChargesWaived": 0.0,
                "feeChargesWrittenOff": 0.0,
                "feeChargesOutstanding": 0.0,
                "penaltyChargesDue": 0.0,
                "penaltyChargesPaid": 0.0,
                "penaltyChargesWaived": 0.0,
                "penaltyChargesWrittenOff": 0.0,
                "penaltyChargesOutstanding": 0.0,
                "totalOriginalDueForPeriod": 1108.000000,
                "totalDueForPeriod": 1108.000000,
                "totalPaidForPeriod": 0.0,
                "totalPaidInAdvanceForPeriod": 0.0,
                "totalPaidLateForPeriod": 0.0,
                "totalWaivedForPeriod": 37.650000,
                "totalWrittenOffForPeriod": 0.0,
                "totalOutstandingForPeriod": 1070.350000,
                "totalActualCostOfLoanForPeriod": 0.000000,
                "totalOverdue": 0.0,
                "totalInstallmentAmountForPeriod": 1108.00
            },
            {
                "dueDate": [
                    2021,
                    1,
                    7
                ],
                "principalDisbursed": 0.0,
                "principalLoanBalanceOutstanding": 0.000000,
                "period": 16,
                "fromDate": [
                    2020,
                    12,
                    31
                ],
                "obligationsMetOnDate": null,
                "complete": false,
                "daysInPeriod": 7,
                "principalOriginalDue": 1082.070000,
                "principalDue": 1082.070000,
                "principalPaid": 0.0,
                "principalWrittenOff": 0.0,
                "principalOutstanding": 1082.070000,
                "taxOnInterestDue": 3.040000,
                "taxOnInterestPaid": 0.0,
                "taxOnInterestOutstanding": 3.040000,
                "interestOriginalDue": 18.980000,
                "interestDue": 18.980000,
                "interestPaid": 0.0,
                "interestWaived": 18.980000,
                "interestWrittenOff": 0.0,
                "interestOutstanding": 0.000000,
                "feeChargesDue": 0.0,
                "feeChargesPaid": 0.0,
                "feeChargesWaived": 0.0,
                "feeChargesWrittenOff": 0.0,
                "feeChargesOutstanding": 0.0,
                "penaltyChargesDue": 0.0,
                "penaltyChargesPaid": 0.0,
                "penaltyChargesWaived": 0.0,
                "penaltyChargesWrittenOff": 0.0,
                "penaltyChargesOutstanding": 0.0,
                "totalOriginalDueForPeriod": 1104.090000,
                "totalDueForPeriod": 1104.090000,
                "totalPaidForPeriod": 0.0,
                "totalPaidInAdvanceForPeriod": 0.0,
                "totalPaidLateForPeriod": 0.0,
                "totalWaivedForPeriod": 18.980000,
                "totalWrittenOffForPeriod": 0.0,
                "totalOutstandingForPeriod": 1085.110000,
                "totalActualCostOfLoanForPeriod": 0.000000,
                "totalOverdue": 0.0,
                "totalInstallmentAmountForPeriod": 1104.09
            }
        ]
    },
    "disbursementDetails": [],
    "feeChargesAtDisbursementCharged": 0.000000,
    "loanCounter": 4,
    "loanProductCounter": 1,
    "multiDisburseLoan": false,
    "canDefineInstallmentAmount": false,
    "canDisburse": false,
    "emiAmountVariations": [],
    "canUseForTopup": false,
    "isTopup": false,
    "closureLoanId": 0,
    "inArrears": true,
    "isNPA": false,
    "overdueCharges": [],
    "daysInMonthType": {
        "id": 1,
        "code": "DaysInMonthType.actual",
        "value": "Actual"
    },
    "daysInYearType": {
        "id": 364,
        "code": "DaysInYearType.days364",
        "value": "364 Days"
    },
    "isInterestRecalculationEnabled": false,
    "createStandingInstructionAtDisbursement": false,
    "paidInAdvance": {
        "paidInAdvance": 0.0
    },
    "isVariableInstallmentsAllowed": false,
    "minimumGap": 0.0,
    "maximumGap": 0.0,
    "isEqualAmortization": false,
    "taxes": [
        {
            "loanId": 13979,
            "amount": 375.736000,
            "loanProductTaxComponent": {
                "loanProductId": 19,
                "percentage": 16.000000,
                "taxComponent": {
                    "id": 5,
                    "percentage": 16.000000,
                    "name": "IVA Interes dev (Grupales)",
                    "debitAccountType": {
                        "id": 1,
                        "code": "accountType.asset",
                        "value": "ASSET"
                    },
                    "debitAccount": {
                        "id": 12,
                        "name": "IVA Intereses Deveng. P/Cobrar Vigente Grupal",
                        "parentId": 0,
                        "glCode": "1304-001-001",
                        "disabled": false,
                        "manualEntriesAllowed": false,
                        "type": null,
                        "usage": null,
                        "description": null,
                        "nameDecorated": null,
                        "tagId": null,
                        "organizationRunningBalance": 0,
                        "accountTypeOptions": null,
                        "usageOptions": null,
                        "assetHeaderAccountOptions": null,
                        "liabilityHeaderAccountOptions": null,
                        "equityHeaderAccountOptions": null,
                        "incomeHeaderAccountOptions": null,
                        "expenseHeaderAccountOptions": null,
                        "allowedAssetsTagOptions": null,
                        "allowedLiabilitiesTagOptions": null,
                        "allowedEquityTagOptions": null,
                        "allowedIncomeTagOptions": null,
                        "allowedExpensesTagOptions": null
                    },
                    "creditAccountType": {
                        "id": 2,
                        "code": "accountType.liability",
                        "value": "LIABILITY"
                    },
                    "creditAccount": {
                        "id": 44,
                        "name": "IVA Devengado",
                        "parentId": 0,
                        "glCode": "2303-004-008",
                        "disabled": false,
                        "manualEntriesAllowed": false,
                        "type": null,
                        "usage": null,
                        "description": null,
                        "nameDecorated": null,
                        "tagId": null,
                        "organizationRunningBalance": 0,
                        "accountTypeOptions": null,
                        "usageOptions": null,
                        "assetHeaderAccountOptions": null,
                        "liabilityHeaderAccountOptions": null,
                        "equityHeaderAccountOptions": null,
                        "incomeHeaderAccountOptions": null,
                        "expenseHeaderAccountOptions": null,
                        "allowedAssetsTagOptions": null,
                        "allowedLiabilitiesTagOptions": null,
                        "allowedEquityTagOptions": null,
                        "allowedIncomeTagOptions": null,
                        "allowedExpensesTagOptions": null
                    },
                    "startDate": [
                        2019,
                        4,
                        22
                    ],
                    "taxComponentHistories": [
                        {
                            "percentage": 0.0,
                            "startDate": null,
                            "endDate": null
                        }
                    ],
                    "glAccountOptions": null,
                    "glAccountTypeOptions": null
                }
            }
        }
    ]
}